apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: site1pool1bridge1
  namespace: tableau
  labels:
    app: site1pool1bridge1
spec:
  serviceName: "site1pool1bridge1"
  replicas: 2
  selector:
    matchLabels:
      app: site1pool1bridge1
  template:
    spec:
      containers:
        - name: site1pool1bridge1
  