apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx
  - ../base/bridge
patches:
  - path: nginx-values.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=nginx
  - path: bridge-values.yaml
    target:
      kind: StatefulSet
      labelSelector: app=site1pool1bridge1
