apiVersion: v1
kind: Service
metadata:
  name: site1pool1bridge1
  namespace: tableau
  labels:
    app.kubernetes.io/name: site1pool1bridge1
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: site1pool1bridge1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: site1pool1bridge1
  namespace: tableau
spec:
  serviceName: "site1pool1bridge1"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: site1pool1bridge1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: site1pool1bridge1
    spec:
      containers:
        - env:
            - name: SITE
              value: "change_me"
            - name: USEREMAIL
              value: "change_me@tableau.com"
            - name: SERVERPOD
              value: "change_me"
          image: "change_me"
          name: site1pool1bridge1
          volumeMounts:
            - name: secret
              mountPath: "/etc/secret"
          resources: {}
          imagePullPolicy: IfNotPresent
      volumes:
        - name: secret
          secret:
            secretName: bridgesecret
            optional: false
  